version: '3'

services:
  api_dev:
    build:
      context: .
      target: development
    command: npm run start:dev
    container_name: api_istay
    restart: always
    ports:
      - $API_PORT:3000
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14.5
    container_name: db_istay
    hostname: db
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - db_istay:/var/lib/postgresql/data/

  adminer:
    image: adminer
    container_name: adminer_istay
    restart: always
    ports:
      - $ADMIN_PORT:8080

  files:
    image: nginx:alpine
    restart: always
    volumes:
      - $FILE_ROOT:/usr/share/nginx/html
    ports:
      - $FILE_PORT:80

  redis:
    image: 'redis:alpine'
    container_name: redis_istay
    hostname: redis
    restart: unless-stopped

volumes:
  db_istay:
